### ISSUE TITLE
Jwt Token 다루기 (Header, Cookie)

### ISSUE THREAD

**Issue by woo-yu** [Ourdus/OURDUS_FE#18]
## Authentication

웹 사이트를 이용할 때엔 개개인의 고유 권한을 부여하기 위해 회원을 등록하고, 로그인한다.  
그렇다면 *사용자가 로그인 했다* 는 정보는 서버에서는 어떻게 인식할까?    

![image](https://user-images.githubusercontent.com/59992230/108954033-7f2de280-76af-11eb-8400-f2c108d3a5ff.png)

사용자가 로그인 정보(id, pw)를 알맞게 보내면, 서버에서는 이를 DB에 저장된 회원 정보와 매치하고  
이 사람은 회원입니다. 라는 증표로 '세션ID or Token'을 발급해서 보내준다.  

로그인에 활용되는 대표적인 방식으로 **Session**과 **Token**의 방식이 있는데, 
우리가 프로젝트에서 사용하는 방식은 Token 중에서도 **Jwt Token**입니다.
(Session은 대표적인 문제점으로 세션 동기화, DB 과부화, CORS 문제 등등... 이 있으니 자세한 내용은 검색을 추천합니다.)
 

## Token은 어떻게 주고받고, 어디에 저장되나?
[참고하면 좋은 링크](https://www.webagam.com/pages/2018/10/24/how-to-use-jwt-tokens-for-secure-access/)

![image](https://user-images.githubusercontent.com/59992230/108955931-493e2d80-76b2-11eb-82a0-2091035d7bf2.png)

서버와 클라이언트가 (쉽게말하면 우리의 `nodejs로 실행된 react code+브라우저`와 `springboot+was`) HTTP 통신을 이용해 token을 주고받을 땐 Header, Cookie 등을 활용하여 주고받을 수 있다.
현재 우리가 주고받는 형식은 다음과 같다.

1. **로그인**

  - Front의 React 코드
```
    axios
        .post('/api/user/login',data)
        .then((response) => {
          const accessToken = response.data.response.data;
          setJwt(accessToken);
          history.push('/main');      
        })

export const setJwt = (token) => {
    instance.defaults.headers.common['jwt-auth-token'] = token;
    setCookie('jwt-auth-token', token);
}
```
  - Backend의 Spring Boot 코드
```
@PostMapping("/user/login")
    public ApiResult<Map<String,Object>> login(HttpServletResponse res, @RequestBody UserDTO userdto){
        Map<String,Object> resultMap = new HashMap<>();
          ...(생략)...
            String token = jwtService.create(loginUser);
            res.setHeader("jwt-auth-token",token);
            resultMap.put("data",token);
          ...(생략)...
        return OK(resultMap);
    }
```

서버에서는 로그인시 정보가 일치하면 token을 생성하고 Header와 requestbody로 보내준다.  
 (원래는 Header로만 보내주었으나, response로 받는 방법이 헷갈려서 requestbody 안에도 담아줌)
클라이언트에서는 받은 토큰을 header와 cookie에 둘 다 담아준다.

2. **token이 필요한(/api/t로 시작) 정보 요청**

  - Front의 React 코드
```
export const getJwt = (uri) => {
    instance.defaults.headers.common['jwt-auth-token'] = getCookie('jwt-auth-token');
    return axios
    .get(uri,{
      headers:{
      'jwt-auth-token': instance.defaults.headers.common['jwt-auth-token']
      }
    })
}
```
  - Backend의 Spring Boot 코드
```
@GetMapping("/t/user/info")
    public ApiResult<UserDTO> getInfo(HttpServletRequest req){
        Long id = Long.valueOf(String.valueOf(jwtService.get(req.getHeader("jwt-auth-token")).get("UserId")));
        User user =userService.getUserInfo(id);
        ...(생략)...
```
담겨져있던 cookie에서 jwt 정보를 꺼내와서 header에 넣고, 이를 서버단에 요청을 보낸다.  
서버에서는 HttpServletRequest를 이용해 request의 header 정보에 담긴 token을 꺼내어 인증한다.  

3. **그동안 삽질했던 내역**
1에서 받은 token은 사용자가 어떤 페이지를 들어가도(로그아웃과 회원탈퇴를 제외한) 유지가 되어야하므로 (물론 시간제한은 존재) 그걸 계속 담고다녀야한다.  이걸 header로 받았을때 계속 유지시켜주려고 history를 이용했는데, 그러면 새로고침이나 주소창에 url을 직접 입력해서 들어갈 경우엔 헤더가 말끔하게 사라진다...^^  
  
그래서 결국엔 cookie에 token 정보를 달고다니기로 했고,    
서버단이랑 주고받는 방법은 header로 계속 담아서 보낼지, httponly를 이용한 cookie로 보낼지 고민해봐야할듯. [참고](https://stackoverflow.com/questions/31068888/jwt-authentication-cookie-vs-header)

**Comment by Kimbangg** [comment]
도움이가 너무나도 되버렸씁니다~~
